# general
seed: 42
workers: 8

# train options
batch_size: 512
image_size: 224
start_epoch: 0
epochs: 200
dataset: "mnist" # CIFAR-10 / CIFAR-100 / STL-10 / ImageNet-10 / ImageNet-dogs / tiny-ImageNet

# model options
feature_dim: 10
model_path: "save/mnist"
reload: False

# loss options
learning_rate: 0.001
weight_decay: 0.
instance_temperature: 0.5
cluster_temperature: 1.0
