# general
seed: 42
workers: 8

# train options
batch_size: 300
image_size: 224
start_epoch: 0
epochs: 200
dataset: "sparse_8_dense_1_dense_1" # CIFAR-10 / CIFAR-100 / STL-10 / ImageNet-10 / ImageNet-dogs / tiny-ImageNet

# model options
feature_dim: 2
model_path: "save/sparse_8_dense_1_dense_1"
reload: False

# loss options
learning_rate: 0.0003
weight_decay: 0.
instance_temperature: 0.5
cluster_temperature: 1.0
